#This is the cloudbuild file that generates the new scoreboard
# run on a trigger in google cloud builds when it detects a modification to a file in /bots


timeout: 9001s #2.5 hour time-out
options:
#  machineType: 'E2_MEDIUM' #could be 32 as well 'N1_HIGHCPU_32'
steps:

# spin up a docker container to pull the latest version of the program
- name: 'jupyter/scipy-notebook:notebook-6.4.4'
  entrypoint: 'bash'
  env:
  - 'DOCKER=1'
  args:
  - -c
  - |
    pwd
    whoami
    ls -la /home/jovyan
    ls -la
    python3 scoreboard.py $(git diff --name-only HEAD HEAD~1)
    ls -la /home/jovyan

# save output json file to cloud storage
artifacts:
  objects:
    location: gs://gops-results/
    paths:
      - /home/jovyan/data_out.json
      - /home/jovyan/scoreboard_out.md