#This cloudbuild.yaml runs regression on all bots to make sure they can all play correctly.


steps:

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/docker', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'run', 'gcr.io/$PROJECT_ID/docker']


images:
- 'gcr.io/$PROJECT_ID/docker'